version: "3"
services:
    web:
        build:
            context: ./app
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - app:/app

volumes:
    app:
